apiVersion: v1
kind: ReplicationController
metadata:
  name: redis-leader
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  labels:
    app: redis
    role: leader
    tier: backend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   app: guestbook
  #   role: leader
  #   tier: backend
  template:
    metadata:
      labels:
        app: redis
        role: leader
        tier: backend
    spec:
      containers:
      - name: leader
        image: "docker.io/redis:6.0.5"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
